main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("posts.urls"))
]

main/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('<slug>/', views.DetailView.as_view(), name='post_detail'),
]

main/posts/models.py
from turtle import ondrag
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import ModelBase
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.conf import settings

# Create your models here.

STATUS = (
    (0,"On_review"),
    (1,"Published")
)

class Post(models.Model):
     author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
     title = models.CharField(max_length=200)
     slug = models.SlugField(max_length=200, unique=True, default=0)  #serve a fare un regex per indicizzare bene il titolo e renderlo ez to read
     text = models.TextField()
     created_date = models.DateTimeField(default=timezone.now)
     published_date = models.DateTimeField(blank=True, null=True)
     status = models.IntegerField(choices=STATUS, default=0)

     def publish(self):
         self.published_date = timezone.now()
         self.save()

     def __str__(self):
         return self.title

main/posts/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'latest_post'

    def get_queryset(self):
        """Return the last five published posts."""
        return Post.objects.order_by('-published_date')[:5]
    
class DetailView(generic.DetailView):
    model = Post
    template_name = 'posts/post_detail.html'

main/posts/templates/posts/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Django Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:home' %}">Django Blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="https://www.instagram.com/feno99">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Injection -->
        {% endblock content %}
    </body>
</html>

main/posts/templates/posts/index.html
{% extends 'posts/base.html' %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in latest_post %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} <br> Posted: {{ post.published_date}} </p>
                    <p class="card-text">{{post.text|slice:":200" }}</p>
                    <a href="{% url 'posts:post_detail' post.slug  %}" class="btn btn-outline-success">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}

main/posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_date }}</p>
        <p class="card-text ">{{ object.text | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}